using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ADOFAI_AP.Patches
{
    internal class Data_AP
    {
        public static Dictionary<string, bool> ItemsReceived = new Dictionary<string, bool>()
        {

            { "Key_Level_1-1", true },
            { "Key_Level_1-2", true },
            { "Key_Level_1-3", true },
            { "Key_Level_1-4", true },
            { "Key_Level_1-5", true },
            { "Key_Level_1-6", true },
            { "Key_Level_1-X", true },
            { "Key_Level_2-1", false },
            { "Key_Level_2-2", false },
            { "Key_Level_2-3", false },
            { "Key_Level_2-X", false },
            { "Key_Level_3-1", false },
            { "Key_Level_3-2", false },
            { "Key_Level_3-3", false },
            { "Key_Level_3-4", false },
            { "Key_Level_3-5", false },
            { "Key_Level_3-6", false },
            { "Key_Level_3-X", false },
            { "Key_Level_4-1", false },
            { "Key_Level_4-2", false },
            { "Key_Level_4-3", false },
            { "Key_Level_4-4", false },
            { "Key_Level_4-5", false },
            { "Key_Level_4-X", false },
            { "Key_Level_5-1", false },
            { "Key_Level_5-2", false },
            { "Key_Level_5-3", false },
            { "Key_Level_5-4", false },
            { "Key_Level_5-X", false },
            { "Key_Level_6-1", false },
            { "Key_Level_6-2", false },
            { "Key_Level_6-3", false },
            { "Key_Level_6-4", false },
            { "Key_Level_6-X", false },
            { "Key_Level_7-1", false },
            { "Key_Level_7-2", false },
            { "Key_Level_7-3", false },
            { "Key_Level_7-4", false },
            { "Key_Level_7-5", false },
            { "Key_Level_7-X", false },
            { "Key_Level_8-1", false },
            { "Key_Level_8-2", false },
            { "Key_Level_8-3", false },
            { "Key_Level_8-4", false },
            { "Key_Level_8-5", false },
            { "Key_Level_8-6", false },
            { "Key_Level_8-7", false },
            { "Key_Level_8-8", false },
            { "Key_Level_8-X", false },
            { "Key_Level_9-1", false },
            { "Key_Level_9-2", false },
            { "Key_Level_9-3", false },
            { "Key_Level_9-4", false },
            { "Key_Level_9-5", false },
            { "Key_Level_9-X", false },
            { "Key_Level_10-1", false },
            { "Key_Level_10-2", false },
            { "Key_Level_10-3", false },
            { "Key_Level_10-4", false },
            { "Key_Level_10-5", false },
            { "Key_Level_10-6", false },
            { "Key_Level_10-7", false },
            { "Key_Level_10-8", false },
            { "Key_Level_10-X", false },
            { "Key_Level_11-1", false },
            { "Key_Level_11-2", false },
            { "Key_Level_11-3", false },
            { "Key_Level_11-4", false },
            { "Key_Level_11-5", false },
            { "Key_Level_11-6", false },
            { "Key_Level_11-X", false },
            { "Key_Level_12-1", false },
            { "Key_Level_12-2", false },
            { "Key_Level_12-3", false },
            { "Key_Level_12-4", false },
            { "Key_Level_12-5", false },
            { "Key_Level_12-6", false },
            { "Key_Level_12-X", false }
        };

        public static Dictionary<string, bool> LocationsChecked = new Dictionary<string, bool>
        {
            { "1-1", false },
            { "1-2", false },
            { "1-3", false },
            { "1-4", false },
            { "1-5", false },
            { "1-6", false },
            { "1-X", false },
            { "2-1", false },
            { "2-2", false },
            { "2-3", false },
            { "2-X", false },
            { "3-1", false },
            { "3-2", false },
            { "3-3", false },
            { "3-4", false },
            { "3-5", false },
            { "3-6", false },
            { "3-X", false },
            { "4-1", false },
            { "4-2", false },
            { "4-3", false },
            { "4-4", false },
            { "4-5", false },
            { "4-X", false },
            { "5-1", false },
            { "5-2", false },
            { "5-3", false },
            { "5-4", false },
            { "5-X", false },
            { "6-1", false },
            { "6-2", false },
            { "6-3", false },
            { "6-4", false },
            { "6-X", false },
            { "7-1", false },
            { "7-2", false },
            { "7-3", false },
            { "7-4", false },
            { "7-5", false },
            { "7-X", false },
            { "8-1", false },
            { "8-2", false },
            { "8-3", false },
            { "8-4", false },
            { "8-5", false },
            { "8-6", false },
            { "8-7", false },
            { "8-8", false },
            { "8-X", false },
            { "9-1", false },
            { "9-2", false },
            { "9-3", false },
            { "9-4", false },
            { "9-5", false },
            { "9-X", false },
            { "10-1", false },
            { "10-2", false },
            { "10-3", false },
            { "10-4", false },
            { "10-5", false },
            { "10-6", false },
            { "10-7", false },
            { "10-8", false },
            { "10-X", false },
            { "11-1", false },
            { "11-2", false },
            { "11-3", false },
            { "11-4", false },
            { "11-5", false },
            { "11-6", false },
            { "11-X", false },
            { "12-1", false },
            { "12-2", false },
            { "12-3", false },
            { "12-4", false },
            { "12-5", false },
            { "12-6", false },
            { "12-X", false }
        };
    }
}
